package.json

Currently if i use with react native 0.59.0 yarn will warn about unmet dependencies due to peerDependencies for react native includes only `^0.57`
React Native 0.59 has just released.
No breaking change for Image Editor (Image Store still remain in react native)

fix(npm): Support React Native up to 0.59

---

typings/index.d.ts

Current typing for ImageCropData.resizeMode is wrong
Currently it typed as object instead of string of ("contain" | "cover" | "stretch")
typings is not included in current npm release

fix(typings): Wrong type for ImageCropData.resizeMode

---

android/src/main/java/com/reactnativecommunity/imageeditor/ImageEditorModule.java

Reference: https://developer.android.com/topic/performance/graphics/load-bitmap

fix(android): Wrong sample size exit logic

---

ios/RNCImageEditor.m
react-native-image-editor.podspec

Project link with CocoaPods can't compile due to can't find `<RCTImage/RCTImageUtils.h>`
Sorry that I didn't test before submit #15
I verified that my CI is green before submit this PR.
I also test with new project without cocoa pod.

fix(ios) Can't compile when link with pod

---

android/src/main/java/com/reactnativecommunity/imageeditor/ImageEditorModule.java

In cropAndResize() there is code for read image dimension but the dimension have never been used. So I remove the code.
Note: There is no usage for `options` anywhere in the function.

optimize(android): Remove unused code in cropAndResize()

---

README.md

`resizeMode` works only in iOS with `contain` as the default value and in Android it's always `cover`.
Close #21

doc(README): Add more info about resizeMode

---

ios/RNCFileSystem.h
ios/RNCFileSystem.m
ios/RNCImageEditor.m
ios/RNCImageEditor.xcodeproj/project.pbxproj
ios/RNCImageUtils.h
ios/RNCImageUtils.m

feat: use own implementation to save cropped images on ios

---

README.md
android/src/main/java/com/reactnativecommunity/imageeditor/ImageEditorModule.java
example/src/App.js
ios/RNCImageEditor.m
lib/ImageEditor.js
typings/index.d.ts

Currently the api use callback pattern instead of easier to use [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) api.
None
Test with example app for both Android and iOS
| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |

BREAKING CHANGE: Use promise instead of callback

---

android/src/main/java/com/reactnativecommunity/imageeditor/ImageEditorModule.java

This library is using ContentProvider on Android as a mean to read image data and as such should accept all schemes handled by ContentProvider. Before this PR only URIs with file and content schemas were recognized as local URIs . This PR adds android.resource scheme what enables us to read apps resources.
1. Try to read any app asset such as "android.resource://<app-package-name>/drawable/<some-image-name>.png"
Adding some android asset to the app and trying to crop it.
1. Try to read any app asset such as "android.resource://<app-package-name>/drawable/<some-image-name>.png"
EX: User is able to read that asset
AR: User is not able to read that asset
| OS      | Implemented |
| ------- | :---------: |
| Android |    ✅   |
- [X ] I have tested this on a device and a simulator

fix: Add missing ContentResolver scheme

---

ios/RNCImageEditor.m

Fixes #37 This PR makes it possible to crop transparent images on ios with preserving transparent background. On Android it's already supported.

feat: make it possible to crop transparent images on ios

---

ios/RNCImageEditor.m

This pull request saves the cropped image as a JPEG in iOS, reflecting the behavior of the previous library.
Android also preforms the same function.

iOS - determine the output image type from the input image type

---

android/build.gradle
android/src/main/AndroidManifestNew.xml

fix: incompatibility with AGP 8 & remove jcenter
- add missing namespace field in `build.gradle` to make it compatible with Android Gradle Plugin 8 (https://github.com/react-native-community/discussions-and-proposals/issues/671)
- replace jcenter with mavencentral
Create test 0.73 RN app, install the library and run the app

fix: incompatibility with AGP 8 & remove jcenter

---

.github/actions/build-app/action.yml
.github/actions/install-dependencies/action.yml
.github/actions/lock-java-ver/action.yml
.github/actions/lock-nodejs-ver/action.yml
.github/actions/lock-ruby-ver/action.yml
.github/workflows/main.yml

Setup Github Actions
- eslint
- flow 
- cache
- Android build (multiple versions next->0.73.0-rc.3, latest->0.72.6, 0.71-stable->0.71.14)
- iOS buid (multiple versions: next->0.73.0-rc.3, latest->0.72.6, 0.71-stable->0.71.14)
Tested on my fork: https://github.com/retyui/react-native-image-editor/actions/runs/6718981645

Setup Github Actions

---

package.json

1. this library is never used `react`
2. npm 7 and above will block installations if an upstream dependency conflict is present that cannot be automatically resolved.
fix: 
- https://github.com/callstack/react-native-image-editor/issues/114
- https://github.com/callstack/react-native-image-editor/issues/105
- https://github.com/callstack/react-native-image-editor/issues/101
- https://github.com/callstack/react-native-image-editor/issues/93
- https://github.com/callstack/react-native-image-editor/issues/79
- https://github.com/callstack/react-native-image-editor/issues/70
- https://github.com/callstack/react-native-image-editor/issues/60
```tsx
npm -v # 7 or above
npx react-native init tmpRN71 --version 0.71.x --npm
cd tmpRN71
npm install /path/to/image-editor
```

Fix npm install for versions 7 and higher.

---

README.md
android/src/main/java/com/reactnativecommunity/imageeditor/ImageEditorModuleImpl.kt
ios/RNCImageEditor.mm
src/NativeRNCImageEditor.ts

Allow to change quality of the resulting image via passing `quality: number` prop. Used the default values without making any breaking changes.
Example:
https://github.com/callstack/react-native-image-editor/assets/4661784/81212d46-6e45-4f1c-bd18-fffa5fbf341d

feature: Add compression quality prop

---

android/src/main/java/com/reactnativecommunity/imageeditor/ImageEditorModuleImpl.kt

- Fix issue: https://github.com/callstack/react-native-image-editor/issues/68
Try cropping the base64 image; it works nicely on iOS but crashes on Android. 
```tsx
const base64Uri = 'data:image/jpg;base64, ...';
ImageEditor.cropImage(base64Uri, {
offset: {x: 0, y: 0},
size: {width: 100, height:100},
})
```

fix: Allow to use base64 uri on Android

---

README.md
src/index.ts
src/index.web.ts
tsconfig.json

Make module cross-platform:
- Issue: https://github.com/callstack/react-native-image-editor/issues/47
- Add Web support
- Add a new optional prop `format?: 'jpeg' | 'png' | 'webp'`
- Update README
1. Create a new Expo project 
```bash
npx create-expo-app -t expo-template-blank-typescript
```
2. Run web `yarn web`:
3. Link a library `yarn add /path/to/package/image-editor` locally 
4. Try to crop image:
```tsx
import ImageEditor from '@react-native-community/image-editor'
ImageEditor.cropImage('https://images.pexels.com/photos/842711/pexels-photo-842711.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', {
"resizeMode": "cover",
"offset": {
"x": 1125,
"y": 750
},
"size": {
"width": 1125,
"height": 750
},
"quality": 0.7,
"format": "jpeg"
})
```
**Video:** …

feature: Add web support

---

android/src/main/java/com/reactnativecommunity/imageeditor/ImageEditorModuleImpl.kt

After merging this PR users will be able to crop images with different exif orientation
- Issue: https://github.com/callstack/react-native-image-editor/issues/111
- Issue: https://github.com/callstack/react-native-image-editor/issues/54
> read more: https://jdhao.github.io/2019/07/31/image_rotation_exif_info/
- https://github.com/recurser/exif-orientation-examples
**Orientation (0, 90, 180, 270):**
<table>
<tbody>
<tr>
<td>
Before
</td>
<td>
After
</td>
</tr>
<tr>
<td>
https://github.com/callstack/react-native-image-editor/assets/4661784/47e396ed-03f1-41b7-a395-aae56ac71c47
</td>
<td>
https://github.com/callstack/react-native-image-editor/assets/4661784/384ff6de-d6be-4964-b047-c1a8e05ab029
</td>
</tr>
</tbody>
</table>

fix: Cropping an image while considering ExifInterface.TAG_ORIENTATION on Android

---

README.md
android/src/main/java/com/reactnativecommunity/imageeditor/ImageEditorModuleImpl.kt
example/ios/Podfile.lock
example/src/SquareImageCropper.tsx
ios/RNCImageEditor.mm
src/NativeRNCImageEditor.ts
src/index.ts
src/index.web.ts
src/types.ts

Part of `4.x` release: Convert a `uri` crop result to an `object`
Examples: 
```json
// web
{
"width": 1125,
"height": 750,
"name": "ReactNative_cropped_image.jpeg",
"size": 283213,
"path": "blob:http://localhost:8082/43ff7a16-c464-4130-a3d2-95286bae46b1",
"uri": "data:image/jpeg;base64,/9j/4A|"
}
// android
{
"height": 600,
"size": 31520,
"name": "ReactNative_cropped_image_5129169684629022727.jpg",
"width": 800,
"uri": "file:///data/user/0/com.rn73/cache/ReactNative_cropped_image_5129169684629022727.jpg",
"path": "/data/user/0/com.rn73/cache/ReactNative_cropped_image_5129169684629022727.jpg"
}
// ios
{
"path": "/Users/davydnarbutovich/Library/Developer/CoreSimulator/Devices/0CA37DFB-8AF0-4714-A849-82E2EE03634F/data/Containers/Data/Application/AD103DB7-10DA-4D4E-A7DD-BDCE371A961D/Library/C …
```

feature: [web/android/ios] Upon success, return more image information

---

README.md
android/src/main/java/com/reactnativecommunity/imageeditor/ImageEditorModuleImpl.kt
ios/RNCImageEditor.mm
package.json
src/NativeRNCImageEditor.ts
src/__typetests__/index.ts
src/index.ts
src/index.web.ts
src/types.ts

Changes
- Update [README.md](https://github.com/callstack/react-native-image-editor/blob/ce8f6523c2fb8a3b24df2638afa70b9c1eca5072/README.md#react-native-image-editor)
- Add `base64` output support
- Add a new result prop `type: 'image/jpeg' | 'image/webp' | 'image/png'`
- Add Typescript tests
...

feature: Add base64 output

---

README.md
android/src/main/java/com/reactnativecommunity/imageeditor/ImageEditorModuleImpl.kt
ios/RNCImageEditor.mm
src/NativeRNCImageEditor.ts
src/index.ts
src/index.web.ts
src/types.ts

Fix: https://github.com/callstack/react-native-image-editor/issues/66
**Data**
```js
headers: {
'x-string': 'my string',
},
```
**Android**
**iOS**
**Web**

Allow pass `headers`

---

android/src/main/java/com/reactnativecommunity/imageeditor/ImageEditorModuleImpl.kt
example/ios/Podfile.lock
example/package.json
example/src/SquareImageCropper.tsx
example/yarn.lock

Fixes #150
I added a "scale" to the test app, so that you can test with a lot of downscaling of the image. The bug can reproduced by running the example and revert the fixed code in `/imageeditor/ImageEditorModuleImpl.kt`, then set the scale to less than 0.5. With the fixed code in `/imageeditor/ImageEditorModuleImpl.kt`, the issue is gone

Fix bitmap crop/scaling for android

---

android/src/main/java/com/reactnativecommunity/imageeditor/ImageEditorModuleImpl.kt

Issue: https://github.com/callstack/react-native-image-editor/issues/161
```java
headers: HashMap<String!, Any!>? // RN 0.74.x
headers: HashMap<String, Any>?   // RN 0.75.x
```
Tested on RN: 0.75.2, 0.74.2

fix: Resolve an issue with the Android build for React Native 0.75.x.
